// <auto-generated />
using System;
using DelabinService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DelabinService.Migrations
{
    [DbContext(typeof(DelabinServiceContext))]
    [Migration("20221219143717_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DelabinService.Models.Data", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Documentid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("fieldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("someData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Documentid");

                    b.ToTable("Data");
                });

            modelBuilder.Entity("DelabinService.Models.Document", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DelabinService.Models.Data", b =>
                {
                    b.HasOne("DelabinService.Models.Document", null)
                        .WithMany("data")
                        .HasForeignKey("Documentid");
                });

            modelBuilder.Entity("DelabinService.Models.Document", b =>
                {
                    b.Navigation("data");
                });
#pragma warning restore 612, 618
        }
    }
}
